//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoWork.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AuthenticatedUser
    {
        [Required(ErrorMessage ="buoc nhap")]
        public string Email { get; set; }
        [Required(ErrorMessage = "buoc nhap")]
        public string passwords { get; set; }
        public string Role { get; set; }
        public string phoneNumber { get; set; }
        public string FullName { get; set; }
        public bool isActive { get; set; }
        public string Avatar { get; set; }
        public Nullable<bool> isBanned { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Client Client { get; set; }
        public virtual Photographer Photographer { get; set; }
    }
}
