//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageDetail
    {
        public Nullable<decimal> deposit { get; set; }
        public Nullable<decimal> startingPrice { get; set; }
        public string Description { get; set; }
        public string PackageID { get; set; }
        public string ServiceID { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Service Service { get; set; }
    }
}
