//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotographerSkill
    {
        public string SkillID { get; set; }
        public string PhotographerID { get; set; }
        public string Experience { get; set; }
    
        public virtual Photographer Photographer { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
